Change travis CI tests versions
Version 1.1.2 is being removed due to and error on the github.com/codegangsta/cli@v1.20.0 dependency:
````
../../codegangsta/cli/context.go:170: undefined: flag.Getter
```

Seems codegangsta/cli is using go's flag.Getter that was only [added in go v1.2](https://github.com/golang/go/commit/49b3301f4ce2a9e21ac076ed53d4bd6e775e748d)

Other versions were replaced by 1.11.4 because the project started using go modules